### ISSUE TITLE
[Feature Request] Getter for sprite's pos and size in the atlas

### ISSUE THREAD

**Issue by flamendless** [EngineerSmith/Runtime-TextureAtlas#1]
Something like:
```lua
local x, y, w, h = atlas:get_quad("duck")
```

**Comment by EngineerSmith** [comment]
I was going to add this function, but then I figured it would waste a few table calls for just doing `atlas.quads["duck"]:getViewport()`  instead. Thanks for the suggestion, I'll throw it in for the sake of making it user friendly, while those who want to save those few cycles can inline it
